name: Assign

on:
  schedule:
    - cron: '*/59 * * * *'
  issue_comment:
    types: [created]

jobs:
  slash_assign:
    if: >
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/assign')) ||
      github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Assign the user or unassign stale assignments
        uses: JasonEtco/slash-assign-action@v0.0.3
        with:
          assigned_label: Assigned
          days_until_warning: 7
          days_until_unassign: 14
